#include "src/game/envfx_snow.h"

const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Half_Closed_Eyes__SKIN__0),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Half_Closed_Eyes__SKIN__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Closed_Eyes__SKIN__1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Closed_Eyes__SKIN__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Left_Eyes__SKIN__2),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Left_Eyes__SKIN__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Right_Eyes__SKIN__3),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Right_Eyes__SKIN__3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Up_Eyes__SKIN__4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Up_Eyes__SKIN__4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Down_Eyes__SKIN__5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Down_Eyes__SKIN__5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Dead_Eyes__SKIN__6),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Dead_Eyes__SKIN__6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt1),
			GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt2),
			GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt3),
			GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt4),
			GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt5),
			GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt6),
			GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, dekulink_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, dekulink_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, dekulink_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, dekulink_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, dekulink_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_Metal_Mario_Switch_Option_Metal_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Metal_Mario_Switch_Option_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_Metal_Mario_Switch_Option_Metal_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, dekulink_Metal_Mario_Switch_Option_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_Metal_Mario_Switch_Option_Metal_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, dekulink_Metal_Mario_Switch_Option_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_Metal_Mario_Switch_Option_Metal_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, dekulink_Metal_Mario_Switch_Option_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_Metal_Mario_Switch_Option_Metal_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, dekulink_Metal_Mario_Switch_Option_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_Metal_Mario_Switch_Option_Metal_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, dekulink_Metal_Mario_Switch_Option_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Metal_Mario_Switch_Option_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_dekulink_Metal_Mario_Switch_Option_Metal_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Metal_Mario_Switch_Option_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_dekulink_Metal_Mario_Switch_Option_Metal_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, dekulink_Metal_Mario_Switch_Option_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_dekulink_Metal_Mario_Switch_Option_Metal_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, dekulink_Metal_Mario_Switch_Option_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_dekulink_Metal_Mario_Switch_Option_Metal_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, dekulink_Metal_Mario_Switch_Option_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_dekulink_Metal_Mario_Switch_Option_Metal_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, dekulink_Metal_Mario_Switch_Option_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_dekulink_Metal_Mario_Switch_Option_Metal_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, dekulink_Metal_Mario_Switch_Option_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Metal_Mario_Switch_Option_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, dekulink_Metal_Mario_Switch_Option_Butt_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, dekulink_Metal_Mario_Switch_Option_Torso_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Metal_Mario_Switch_Option_Head_DL_mesh_layer_1),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_dekulink_Metal_Mario_Switch_Option_Metal_Capless_Head),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Metal_Mario_Switch_Option_Left_Wing_DL_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Metal_Mario_Switch_Option_Right_Wing_DL_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, dekulink_Metal_Mario_Switch_Option_Left_Arm_Color_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, dekulink_Metal_Mario_Switch_Option_Left_Forearm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Metal_Mario_Switch_Option_Left_Hand_DL_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_dekulink_Metal_Mario_Switch_Option_Metal_Left_Hand_Open),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, dekulink_Metal_Mario_Switch_Option_Right_Arm_Color_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, dekulink_Metal_Mario_Switch_Option_Right_Forearm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Metal_Mario_Switch_Option_Right_Hand_DL_mesh_layer_1),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_dekulink_Metal_Mario_Switch_Option_Metal_Right_Hand_Open),
										GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_dekulink_Metal_Mario_Switch_Option_Metal_Right_Hand_Peace),
										GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_dekulink_Metal_Mario_Switch_Option_Metal_Right_Hand_Cap),
										GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_dekulink_Metal_Mario_Switch_Option_Metal_Right_Hand_Wing_Cap),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, dekulink_Metal_Mario_Switch_Option_Left_Thigh_Color_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, dekulink_Metal_Mario_Switch_Option_Left_Leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, dekulink_Metal_Mario_Switch_Option_Left_Shoe_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, dekulink_Metal_Mario_Switch_Option_Right_Thigh_Color_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, dekulink_Metal_Mario_Switch_Option_Right_Leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Metal_Mario_Switch_Option_Right_Shoe_DL_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_Metal_Mario[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -59, 0, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dekulink_Metal_Mario_Switch_Option_Butt_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ASM(0, geo_move_mario_part_from_parent),
						GEO_ASM(0, geo_mario_tilt_torso),
						GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, dekulink_Metal_Mario_Switch_Option_Torso_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_head_rotation),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Metal_Mario_Switch_Option_Head_DL_mesh_layer_1),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, dekulink_Metal_Mario_Switch_Option_Metal_Capless_Head),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, 126, -15, 33, -133),
										GEO_OPEN_NODE(),
											GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Metal_Mario_Switch_Option_Left_Wing_DL_mesh_layer_1),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, -126, 15, -33, -133),
										GEO_OPEN_NODE(),
											GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Metal_Mario_Switch_Option_Right_Wing_DL_mesh_layer_1),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dekulink_Metal_Mario_Switch_Option_Left_Arm_Color_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, dekulink_Metal_Mario_Switch_Option_Left_Forearm_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(1, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(1, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Metal_Mario_Switch_Option_Left_Hand_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, dekulink_Metal_Mario_Switch_Option_Metal_Left_Hand_Open),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dekulink_Metal_Mario_Switch_Option_Right_Arm_Color_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, dekulink_Metal_Mario_Switch_Option_Right_Forearm_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Metal_Mario_Switch_Option_Right_Hand_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
														GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, dekulink_Metal_Mario_Switch_Option_Metal_Right_Hand_Open),
												GEO_BRANCH(1, dekulink_Metal_Mario_Switch_Option_Metal_Right_Hand_Peace),
												GEO_BRANCH(1, dekulink_Metal_Mario_Switch_Option_Metal_Right_Hand_Cap),
												GEO_BRANCH(1, dekulink_Metal_Mario_Switch_Option_Metal_Right_Hand_Wing_Cap),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dekulink_Metal_Mario_Switch_Option_Left_Thigh_Color_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, dekulink_Metal_Mario_Switch_Option_Left_Leg_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, dekulink_Metal_Mario_Switch_Option_Left_Shoe_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dekulink_Metal_Mario_Switch_Option_Right_Thigh_Color_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, dekulink_Metal_Mario_Switch_Option_Right_Leg_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(2, geo_mario_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Metal_Mario_Switch_Option_Right_Shoe_DL_mesh_layer_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Half_Closed_Eyes__SKIN__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Half_Closed_Eyes__SKIN__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Closed_Eyes__SKIN__1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Closed_Eyes__SKIN__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Left_Eyes__SKIN__2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Left_Eyes__SKIN__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Right_Eyes__SKIN__3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Right_Eyes__SKIN__3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Up_Eyes__SKIN__4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Up_Eyes__SKIN__4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Down_Eyes__SKIN__5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Down_Eyes__SKIN__5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Dead_Eyes__SKIN__6),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Dead_Eyes__SKIN__6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_jump_dekulink_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt1),
			GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt2),
			GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt3),
			GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt4),
			GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt5),
			GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt6),
			GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_jump_dekulink_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, dekulink_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_jump_dekulink_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, dekulink_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_jump_dekulink_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, dekulink_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_jump_dekulink_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, dekulink_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_jump_dekulink_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, dekulink_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Head_DL_mesh_layer_1_mat_override_Half_Closed_Eyes__SKIN__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Head_DL_mesh_layer_1_mat_override_Closed_Eyes__SKIN__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Head_DL_mesh_layer_1_mat_override_Left_Eyes__SKIN__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Head_DL_mesh_layer_1_mat_override_Right_Eyes__SKIN__3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Head_DL_mesh_layer_1_mat_override_Up_Eyes__SKIN__4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Head_DL_mesh_layer_1_mat_override_Down_Eyes__SKIN__5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Head_DL_mesh_layer_1_mat_override_Dead_Eyes__SKIN__6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, -59, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 85, 0, 0, dekulink_Torso_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 110, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Head_DL_mesh_layer_1),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt1),
											GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt2),
											GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt3),
											GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt4),
											GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt5),
											GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt6),
											GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt7),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_jump_dekulink_Capless_Head),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 161, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Left_Wing_DL_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 161, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Right_Wing_DL_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Left_Arm_Color_skinned_mesh_layer_1),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 61, -10, 62, 135, -135, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, -180, -45, -45),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, dekulink_Left_Arm_Color_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 82, 0, 4, -68, -48, 87),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, dekulink_Left_Forearm_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(1, geo_switch_mario_hand),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 80, 0, -21, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_hand_foot_scaler),
															GEO_SCALE(LAYER_FORCE, 65536),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Left_Hand_DL_mesh_layer_1),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_jump_dekulink_Left_Hand_Open),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Right_Arm_Color_skinned_mesh_layer_1),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 60, -10, -63, 45, 45, 180),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 180, -45, -45),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, dekulink_Right_Arm_Color_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 76, 0, -3, dekulink_Right_Forearm_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 83, 0, 20, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Right_Hand_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
														GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_jump_dekulink_Right_Hand_Open),
												GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_jump_dekulink_Right_Hand_Peace),
												GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_jump_dekulink_Right_Hand_Cap),
												GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1_jump_dekulink_Right_Hand_Wing_Cap),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 13, -8, 42, 0, 0, -180),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, 0, -180),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 41, 0, 14, dekulink_Left_Leg_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 56, 0, 14, dekulink_Left_Shoe_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 42, 0, -17, dekulink_Right_Leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 55, 0, -11, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_Right_Shoe_DL_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Head_DL_mesh_layer_1_mat_override_Half_Closed_Eyes__SKIN__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Head_DL_mesh_layer_1_mat_override_Closed_Eyes__SKIN__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Head_DL_mesh_layer_1_mat_override_Left_Eyes__SKIN__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Head_DL_mesh_layer_1_mat_override_Right_Eyes__SKIN__3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Head_DL_mesh_layer_1_mat_override_Up_Eyes__SKIN__4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Head_DL_mesh_layer_1_mat_override_Down_Eyes__SKIN__5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Head_DL_mesh_layer_1_mat_override_Dead_Eyes__SKIN__6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dekulink_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_OPAQUE << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_ALPHA << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_TRANSPARENT << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, -59, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_move_mario_part_from_parent),
										GEO_ASM(0, geo_mario_tilt_torso),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 85, 0, 0, dekulink_Torso_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 110, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_head_rotation),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Head_DL_mesh_layer_1),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt1),
																	GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt2),
																	GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt3),
																	GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt4),
																	GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt5),
																	GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt6),
																	GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt7),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, dekulink_Capless_Head),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 161, -51, 126, -15, 33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_ALPHA, dekulink_Left_Wing_DL_mesh_layer_4),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 161, -51, -126, 15, -33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_ALPHA, dekulink_Right_Wing_DL_mesh_layer_4),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Left_Arm_Color_skinned_mesh_layer_1),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 61, -10, 62, 135, -135, 0),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, -180, -45, -45),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dekulink_Left_Arm_Color_mesh_layer_1),
															GEO_OPEN_NODE(),
																GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 82, 0, 4, -68, -48, 87),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dekulink_Left_Forearm_mesh_layer_1),
																	GEO_OPEN_NODE(),
																		GEO_SWITCH_CASE(1, geo_switch_mario_hand),
																		GEO_OPEN_NODE(),
																			GEO_NODE_START(),
																			GEO_OPEN_NODE(),
																				GEO_ANIMATED_PART(LAYER_OPAQUE, 80, 0, -21, NULL),
																				GEO_OPEN_NODE(),
																					GEO_ASM(1, geo_mario_hand_foot_scaler),
																					GEO_SCALE(LAYER_FORCE, 65536),
																					GEO_OPEN_NODE(),
																						GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Left_Hand_DL_mesh_layer_1),
																					GEO_CLOSE_NODE(),
																				GEO_CLOSE_NODE(),
																			GEO_CLOSE_NODE(),
																			GEO_BRANCH(1, dekulink_Left_Hand_Open),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Right_Arm_Color_skinned_mesh_layer_1),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 60, -10, -63, 45, 45, 180),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 180, -45, -45),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dekulink_Right_Arm_Color_mesh_layer_1),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(LAYER_OPAQUE, 76, 0, -3, dekulink_Right_Forearm_mesh_layer_1),
																GEO_OPEN_NODE(),
																	GEO_SWITCH_CASE(0, geo_switch_mario_hand),
																	GEO_OPEN_NODE(),
																		GEO_NODE_START(),
																		GEO_OPEN_NODE(),
																			GEO_ANIMATED_PART(LAYER_OPAQUE, 83, 0, 20, NULL),
																			GEO_OPEN_NODE(),
																				GEO_ASM(0, geo_mario_hand_foot_scaler),
																				GEO_SCALE(LAYER_FORCE, 65536),
																				GEO_OPEN_NODE(),
																					GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Right_Hand_DL_mesh_layer_1),
																				GEO_CLOSE_NODE(),
																				GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
																			GEO_CLOSE_NODE(),
																		GEO_CLOSE_NODE(),
																		GEO_BRANCH(1, dekulink_Right_Hand_Open),
																		GEO_BRANCH(1, dekulink_Right_Hand_Peace),
																		GEO_BRANCH(1, dekulink_Right_Hand_Cap),
																		GEO_BRANCH(1, dekulink_Right_Hand_Wing_Cap),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 13, -8, 42, 0, 0, -180),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, 0, -180),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 41, 0, 14, dekulink_Left_Leg_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 56, 0, 14, dekulink_Left_Shoe_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 42, 0, -17, dekulink_Right_Leg_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 55, 0, -11, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(2, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_Right_Shoe_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, dekulink_7_LoD_Switch__Unused__opt0_Cap_State_Switch_opt1),
							GEO_BRANCH(1, dekulink_Metal_Mario),
							GEO_BRANCH(1, dekulink_Metal_Mario),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM((LAYER_OPAQUE << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_ALPHA << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_TRANSPARENT << 2) | 1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dekulink_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, dekulink_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dekulink_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
